
# This is the base configuration. 
version: '2'

services:
  # The Python service that provides some basic APIs
  ukwa-access-api:
    image: ukwa/ukwa-access-api
    ports:
     - "8000:8000"

  # OpenWayback for OUKWA
  openwayback:
    image: ukwa/waybacks:2017-style-reset
    ports:
      - "${INTERNAL_IP}:9080:8080"
      - "${INTERNAL_IP}:8090:8090"
    environment:
      - "UKWA_OWB_VERSION=ukwa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/waybacks/wayback-qa/target/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"

  # The main UKWA UI itself
#  ukwa-ui:
#    image: ukwa/ukwa-ui
#    ports:
#     - "9000:9000"

