
# This is the base configuration. 
version: '3.2'

services:
  # The Python service that provides some basic APIs
  ukwa-access-api:
    image: ukwa/ukwa-access-api
    ports:
     - "8000:8000"

  # OpenWayback for OUKWA
  openwayback:
    image: ukwa/waybacks:2017-style-reset
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=ukwa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_URL_PREFIX=https://beta.webarchive.org.uk/wayback"
      - "WAYBACK_PROXY_HOST=192.168.45.25"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST=/usr/local/wayback-config/open-access-whitelist.txt"
      - "WAYBACK_EXCLUDE_FILE=/usr/local/wayback-config/exclude-blacklist.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.60:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"
    volumes:
      - /root/wayback-config:/usr/local/wayback-config

  openwayback-prod:
    image: ukwa/waybacks
    ports:
      - "7080:8080"
      - "7090:8090"
    environment:
      - "UKWA_OWB_VERSION=ukwa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_URL_PREFIX=https://www.webarchive.org.uk/wayback"
      - "WAYBACK_PROXY_HOST=192.168.45.25"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST=/usr/local/wayback-config/open-access-whitelist.txt"
      - "WAYBACK_EXCLUDE_FILE=/usr/local/wayback-config/exclude-blacklist.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.60:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"
    volumes:
      - /root/wayback-config:/usr/local/wayback-config

  pywb:
    image: ukwa/ukwa-pywb
    ports:
      - "8081:8080"
    environment:
      - "WEBHDFS_USER=access"
      - "UKWA_INDEX=xmlquery+http://192.168.45.21:8080/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://192.168.45.60:14000"

  # The main UKWA UI itself
  ukwa-ui:
    image: ukwa/ukwa-ui:alpha
    ports:
     - "7070:8080"
    environment:
     - "ARCHIVE_WEB_LOCATION=https://www.webarchive.org.uk/wayback/archive/"
     - "OFF_SITE_URL=https://www.webarchive.org.uk/wayback/archive/"
     - "SOLR_COLLECTION_SEARCH_PATH=http://192.168.45.241:8983"
     - "SOLR_COLLECTION_SEARCH_REQUEST_HANDLER=/solr/collections/select"
     - "SOLR_FULL_TEXT_SEARCH_PATH=http://192.168.45.33:8983"
     - "SOLR_FULL_TEXT_SEARCH_REQUEST_HANDLER=/solr/all/select"
     - "SOLR_READ_TIMEOUT=6000"
     - "SOLR_CONNECTION_TIMEOUT=6000"
     - "SOLR_USERNAME="
     - "SOLR_PASSWORD="
     - "SOLR_SHOW_STUB_DATA_SERVICE_NOT_AVAILABLE=true"
     - "BL_SMTP_SERVER_HOST=juno.bl.uk"
     - "BL_SMTP_USERNAME="
     - "BL_SMTP_PASSWORD="

  # Mementos
  mementos:
    image: ukwa/mementoweb-webclient
    command: "/mementos/bin/mementos-webclient -Dhttp.proxyHost=194.66.232.92 -Dhttp.proxyPort=3127 -Dconfig.file=/mementos/conf/application.conf -Dpidfile.path=/dev/null"
    ports:
      - "9000:9000"
    environment:
      - "JAVA_OPTS=-Xmx1g -Dhttp.proxyHost=explorer -Dhttp.proxyPort=3127"

  # Shine
  shine:
   image: ukwa/shine
   ports:
     - "9001:9000"
   depends_on:
     - shinedb

  # Access Task Scheduler
  access:
    image: ukwa/ukwa-manage:ingest-ng-phase-2
    command: "luigid"
    ports:
      - "8082:8082"
    volumes:
      - ./prod/access/luigi:/etc/luigi
#      - ./luigid:/var/tmp/luigid
    environment:
      - "ELASTICSEARCH_HOST=access"
      - "ELASTICSEARCH_INDEX_PREFIX=access-tasks"


  # Task state
  taskdb:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=access"
      - "POSTGRES_PASSWORD=access"
      - "POSTGRES_DB=access_task_state"
    ports:
      - "5432:5432"
    volumes:
      - "/data/access-task-db/postgresql:/var/lib/postgresql/data"
      - "/data/access-task-db/postgresql-in-out-box:/var/lib/postgresql/in-out-box"


  # Shine state    
  shinedb:
    image: postgres:9.6.2
    volumes:
      - "/data/shine/postgresql/data:/var/lib/postgresql/data"   
    ports:
      - "5433:5432"  
      
      
  # Providing container level metrics:
  # -------------------------------------------------------------

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9393:8080


