
# This is the base configuration. 
version: '3.2'

services:
  # The Python service that provides some basic APIs
  ukwa-access-api:
    image: ukwa/ukwa-access-api
    ports:
     - "8000:8000"

  # OpenWayback for OUKWA
  openwayback:
    image: ukwa/waybacks:2017-style-reset
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=ukwa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_URL_PREFIX=https://beta.webarchive.org.uk/wayback"
      - "WAYBACK_PROXY_HOST=192.168.45.25"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST=/usr/local/wayback-config/open-access-whitelist.txt"
      - "WAYBACK_EXCLUDE_FILE=/usr/local/wayback-config/exclude-blacklist.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"
    volumes:
      - /root/gitlab/discovery_supervisor/twang/oukwa-wayback-config:/usr/local/wayback-config

  openwayback-prod:
    image: ukwa/waybacks
    ports:
      - "7080:8080"
      - "7090:8090"
    environment:
      - "UKWA_OWB_VERSION=ukwa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_URL_PREFIX=https://www.webarchive.org.uk/wayback"
      - "WAYBACK_PROXY_HOST=192.168.45.25"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST=/usr/local/wayback-config/open-access-whitelist.txt"
      - "WAYBACK_EXCLUDE_FILE=/usr/local/wayback-config/exclude-blacklist.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"
    volumes:
      - /root/gitlab/discovery_supervisor/twang/oukwa-wayback-config:/usr/local/wayback-config

  pywb:
    image: ukwa/ukwa-pywb
    ports:
      - "8180:8080"
      - "8081:8081"
    environment:
      - "WEBHDFS_USER=access"
      - "UKWA_INDEX=xmlquery+http://192.168.45.21:8080/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://192.168.45.13:14000"
    volumes:
      - /root/wayback-config/open-access-whitelist.aclj:/ukwa_pywb/acl/allows.aclj
      - /root/wayback-config/exclude-blacklist.aclj:/ukwa_pywb/acl/blocks.aclj

  # The main UKWA UI itself
  ukwa-ui:
    image: ukwa/ukwa-ui:alpha
    ports:
     - "7070:8080"
    environment:
     - "SET_PROTOCOL_TO_HTTPS=true"
     - "OFF_SITE_URL=https://beta.webarchive.org.uk/wayback/archive/"
     - "SOLR_COLLECTION_SEARCH_PATH=http://192.168.45.241:8983"
     - "SOLR_COLLECTION_SEARCH_REQUEST_HANDLER=/solr/collections/select"
     - "SOLR_FULL_TEXT_SEARCH_PATH=http://192.168.45.33:8983"
     - "SOLR_FULL_TEXT_SEARCH_REQUEST_HANDLER=/solr/all/select"
     - "SOLR_READ_TIMEOUT=60000"
     - "SOLR_CONNECTION_TIMEOUT=60000"
     - "SOLR_USERNAME="
     - "SOLR_PASSWORD="
     - "SOLR_SHOW_STUB_DATA_SERVICE_NOT_AVAILABLE=true"
     - "BL_SMTP_SERVER_HOST=juno.bl.uk"
     - "BL_SMTP_USERNAME="
     - "BL_SMTP_PASSWORD="

  ukwa-ui-pre-alpha:
    image: ukwa/ukwa-ui:pre-alpha
    ports:
     - "6060:8080"
    environment:
     - "SET_PROTOCOL_TO_HTTPS=false"
     - "OFF_SITE_URL=https://alpha.webarchive.org.uk/en/archive/"
     - "SOLR_COLLECTION_SEARCH_PATH=http://192.168.45.241:8983"
     - "SOLR_COLLECTION_SEARCH_REQUEST_HANDLER=/solr/collections/select"
     - "SOLR_FULL_TEXT_SEARCH_PATH=http://192.168.45.33:8983"
     - "SOLR_FULL_TEXT_SEARCH_REQUEST_HANDLER=/solr/all/select"
     - "SOLR_READ_TIMEOUT=60000"
     - "SOLR_CONNECTION_TIMEOUT=60000"
     - "SOLR_USERNAME="
     - "SOLR_PASSWORD="
     - "SOLR_SHOW_STUB_DATA_SERVICE_NOT_AVAILABLE=true"
     - "BL_SMTP_SERVER_HOST=juno.bl.uk"
     - "BL_SMTP_USERNAME="
     - "BL_SMTP_PASSWORD="

  # Shine
  # Basically working, but need to hook in proper database back-end
  shine:
    image: ukwa/shine
    ports:
      - "9001:9000"
    environment:
      - "SOLR_URL=http://192.168.45.70:8983/solr/jisc"

  # Mementos
  mementos:
    image: ukwa/mementoweb-webclient
    command: "/mementos/bin/mementos-webclient -Dhttp.proxyHost=194.66.232.92 -Dhttp.proxyPort=3127 -Dconfig.file=/mementos/conf/application.conf -Dpidfile.path=/dev/null"
    ports:
      - "9000:9000"
    environment:
      - "JAVA_OPTS=-Xmx1g -Dhttp.proxyHost=explorer -Dhttp.proxyPort=3127"

  # Rate limiter for Mementos:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./prod/access/nginx.conf:/etc/nginx/conf.d/default.conf:ro   

  # Access Task Scheduler
  access:
    image: ukwa/ukwa-manage:ingest-ng-phase-2
    command: "luigid"
    ports:
      - "8082:8082"
    volumes:
      - ./prod/access/luigi:/etc/luigi
#      - ./luigid:/var/tmp/luigid
    environment:
      - "ELASTICSEARCH_HOST=access"
      - "ELASTICSEARCH_INDEX_PREFIX=access-tasks"

  # PostgreSQL for storing task state
  taskdb:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=access"
      - "POSTGRES_PASSWORD=access"
      - "POSTGRES_DB=access_task_state"
    ports:
      - "5432:5432"
    volumes:
      - "/data/access-task-db/postgresql:/var/lib/postgresql/data"
      - "/data/access-task-db/postgresql-in-out-box:/var/lib/postgresql/in-out-box"

  # A UI for poking around in PostgreSQL:
  db-ui:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=wa-sysadm@bl.uk"
      - "PGADMIN_DEFAULT_PASSWORD=access"
    ports:
      - 90:80


  # Providing container level metrics:
  # -------------------------------------------------------------

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9393:8080


