
# This is the base configuration. 
version: '2'

services:
  # The Python service that provides some basic APIs
  ukwa-access-api:
    image: ukwa/ukwa-access-api
    ports:
     - "8000:8000"

  # OpenWayback for OUKWA
  openwayback:
    image: ukwa/waybacks:2017-style-reset
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=ukwa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/waybacks/wayback-qa/target/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"

  # The main UKWA UI itself
#  ukwa-ui:
#    image: ukwa/ukwa-ui
#    ports:
#     - "9000:9000"

  # Mementos
  mementos:
    image: ukwa/mementoweb-webclient
    ports:
      - "9000:9000"

  # Access Task Scheduler
  access:
    image: ukwa/ukwa-manage:ingest-ng-phase-2
    ports:
      - "8082:8082"
    volumes:
      - ./prod/access/luigi:/etc/luigi
#      - ./luigid:/var/tmp/luigid


  # ---------------------------------------------------------------------------
  # Until Monitor is up to running Dockerized services we'll run this UI here:
  # ---------------------------------------------------------------------------

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - elasticsearch
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    volumes_from:
      - grafana-storage

  grafana-storage:
    image: busybox
    volumes:
      - ./target/testing/grafana-data:/var/lib/grafana

  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9200:9200"

