INDEX:   &INDEX ${UKWA_INDEX}
ARCHIVE: &ARCHIVE ${UKWA_ARCHIVE}

collections:
    # open access (with access controls) under /archive/
    archive:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        acl_paths:
            - ./acl/blocks.aclj
            - ./acl/allows.aclj

        default_access: block

proxy:
    # collection for proxy mode
    coll: archive
    ca_name: UKWA pywb HTTPS Proxy CA
    ca_file_cache: ./proxy-certs/pywb-ca.pem


# redirect to exact url behavior
redirect_to_exact: true

# enable memento
enable_memento: true

# enable experimental Memento Prefer
enable_prefer: true


locales_root_dir: ./i18n/translations/
locales:
  - en
  - cy

