INDEX: &INDEX xmlquery+http://192.168.45.21:8080/data-heritrix
STORE: &STORE webhdfs://192.168.45.60:14000

collections:
    # reading room collection (locks and blocks only)
    reading-room:
        index_paths: *INDEX
        archive_paths: *STORE

        single-use-lock: true
        acl_paths:
            - ./acl/blocks.aclj

    # open access (with access controls)
    open-access:
        index_paths: *INDEX
        archive_paths: *STORE

        acl_paths:
            - ./acl/blocks.aclj
            - ./acl/allows.aclj

        default_access: block

    # QA no access controls
    qa-access:
        index_paths: *INDEX
        archive_paths: *STORE

proxy:
    coll: qa-access
    ca_name: UKWA pywb HTTPS Proxy CA
    ca_file_cache: ./proxy-certs/pywb-ca.pem
    recording: false

